### ISSUE TITLE
Cannot run tests using the shadowJar plugin in custom plugin

### ISSUE THREAD

**Issue by maranellored** [johnrengelman/shadow#267]
I'm working on a wrapper plugin that wraps the ShadowJar plugin and a couple of other plugins into a single Gradle Plugin that can be imported by users in their projects. 

It works great but I'm running into issues while I try to test my plugin. 

Inside my plugin, I apply the shadow plugin to my project as below 
```groovy
this.project.apply 'com.github.johnrengelman.shadow'
```

In my plugin's build file, I add the shadow jar as a compile time dependency like this - 
```groovy
compile "com.github.jengelman.gradle.plugins:shadow:1.2.4"
```

I run into this error when I try to run my unit tests - 
```
Caused by: java.lang.ClassCastException: org.gradle.api.plugins.JavaPluginConvention cannot be cast to groovy.lang.GroovyObject
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at com.github.jengelman.gradle.plugins.shadow.ShadowJavaPlugin.configureShadowTask(ShadowJavaPlugin.groovy:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.github.jengelman.gradle.plugins.shadow.ShadowJavaPlugin.apply(ShadowJavaPlugin.groovy:35)
	at com.github.jengelman.gradle.plugins.shadow.ShadowJavaPlugin.apply(ShadowJavaPlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:139)
```
I saw that you guys previously ran into this issue because of Gradle API change incompatibilities. See https://github.com/johnrengelman/shadow/issues/217. 

Also, it does look like the Gradle API reverted the original change that was put in as part of https://issues.gradle.org/browse/GRADLE-3455. 
See https://github.com/gradle/gradle/blob/v3.1.0/subprojects/plugins/src/main/groovy/org/gradle/api/plugins/JavaPluginConvention.java

Does this gradle API change also break the ShadowJar build?
Is there anything I could be doing here to fix this on my end? Or do I need to ping the folks on the gradle project to revert their backward incompatible changes? 

**Shadow Version** - 1.2.4
 
**Gradle Version**- 3.1

**Comment by tomasulo** [comment]
I am having the same issues...

**Comment by johnrengelman** [comment]
Have you tried with the latest Gradle versions?

**Comment by maranellored** [comment]
I've just tried this with Gradle 4.0 and it seems to work. 
I'm gonna close this out since its no longer and issue and can be fixed by upgrading Gradle.

Thanks!
