### ISSUE TITLE
Relocation fails task when dependency includes `module-info.class`

### ISSUE THREAD

**Issue by sghill** [johnrengelman/shadow#289]
Please check the (User Guide)[http://imperceptiblethoughts.com/shadow] before submitting "how do I do 'x'?" questions!

The build works when not relocating, but if anything is relocated and a jar with module-info is present, ASM throws an exception.

### Shadow Version
1.2.4

### Gradle Version
3.5

### Expected Behavior
`shadowJar` task succeeds

### Actual Behavior
```
:shadowJar
ex
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:110)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$StreamAction.remapClass(ShadowCopyAction.groovy:256)
```

### Gradle Build Script(s)
```gradle
plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '1.2.4'
}

repositories { jcenter() }

dependencies {
    compile 'org.slf4j:slf4j-api:1.8.0-alpha1' // includes module-info.java
    compile 'com.google.guava:guava:16.0'
}

shadowJar {
   relocate 'com.google', 'shadow.com.google'
}
```

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
Task fails to create shadow jar

**Comment by sghill** [comment]
This is the same issue as #294 and was also fixed with the 2.0.2 release.
