### ISSUE TITLE
shadowJar fails - lower ASM API version

### ISSUE THREAD

**Issue by finalchild** [johnrengelman/shadow#406]
### Shadow Version
4.0.1 (Latest as 20181001)
### Gradle Version
4.10.2 (Latest as 20181001)
### Expected Behavior
shadowJar should work as intended.
### Actual Behavior
java.lang.UnsupportedOperationException (no error message) is thrown from shadow.org.objectweb.asm.ClassVisitor.java:135

https://gitlab.ow2.org/asm/asm/blob/master/asm/src/main/java/org/objectweb/asm/ClassVisitor.java#L130
The error message "This feature requires ASM6" was recently added.

### Gradle Build Script(s)
https://github.com/finalchild/kotlinbukkit/blob/master/build.gradle

Failed CI Build: https://travis-ci.org/finalchild/kotlinbukkit/builds/435489401
Stacktrace: https://pastebin.com/daMmwrbk

**Comment by Hillkorn** [comment]
Actually I had the same problem on some hosts with Oracle Java 1.8.0_181 and going down to asm 6.0 fixed it. But strange is that this problem did not occurred on all systems.

**Comment by petarov** [comment]
Same thing here on Shadow 4.0.1. Downgrade to 2.0.4 fixes it. Thanks @mshatalov!

```
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          11 (Oracle Corporation 11+28-201810021910)
OS:           Mac OS X 10.13.6 x86_64
```

**Comment by AttemptToCallNil** [comment]
My project uses almost the same configuration as the two commenters above, except my OS is Windows 7 SP1 x64. Shadow 4.0.1 works when building with Oracle JDK 10.0.1, but causes a very similar error when building with OpenJDK 11 GA. Shadow 2.0.4 works with both.

**Comment by vyazelenko** [comment]
Same here. I tried upgrade shadow plugin to version **4.0.1** in my https://github.com/vyazelenko/performance-after-eight project but got the following error when trying to build on JDK 11:
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jdk-11:shadowJar'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.UnsupportedOperationException
        at shadow.org.objectweb.asm.ClassVisitor.visitNestHostExperimental(ClassVisitor.java:158)
        at shadow.org.objectweb.asm.commons.ClassRemapper.visitNestHostExperimental(ClassRemapper.java:185)
        at shadow.org.objectweb.asm.ClassReader.accept(ClassReader.java:541)
        at shadow.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        at shadow.org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:201)
        at shadow.org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:96)
        at shadow.org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:81)
        at shadow.org.vafer.jdependency.Clazzpath$addClazzpathUnit.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
        at com.github.jengelman.gradle.plugins.shadow.internal.UnusedTracker$_closure1.doCall(UnusedTracker.groovy:18)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:434)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3287)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3257)
        at org.codehaus.groovy.runtime.dgm$67.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
        at com.github.jengelman.gradle.plugins.shadow.internal.UnusedTracker.<init>(UnusedTracker.groovy:18)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:258)
        at com.github.jengelman.gradle.plugins.shadow.internal.UnusedTracker.forProject(UnusedTracker.groovy:42)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.createCopyAction(ShadowJar.java:83)
        at org.gradle.api.tasks.AbstractCopyTask.copy(AbstractCopyTask.java:178)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.copy(ShadowJar.java:97)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 34 more
```
The **2.0.4** version works.

**Comment by vyazelenko** [comment]
@johnrengelman Any update on this issue?

**Comment by petarov** [comment]
As OP stated above, the problem stems from the Asm dependency, but what's peculiar is that Shadow already uses Asm `6.2.1` [[1]](https://github.com/johnrengelman/shadow/blob/master/gradle/dependencies.gradle#L9) and  the author of Asm says `6.2.1` should work fine with Java 11 [[2]](https://gitlab.ow2.org/asm/asm/issues/317860). I wonder if this is OpenJDK 11 specific. 🤔

**Comment by vyazelenko** [comment]
@petarov As far as I can tell by looking at the ASM code it seems that `nestmates feauture` only works with ASM 7
In **6.2.1** the code in `ClassVisitor` looks like this:
```
 @Deprecated
  public void visitNestHostExperimental(final String nestHost) {
    if (api < Opcodes.ASM7_EXPERIMENTAL) {
      throw new UnsupportedOperationException();
    }
    if (cv != null) {
      cv.visitNestHostExperimental(nestHost);
    }
  }
```
And in **7.0-BETA** like this:
```
 public void visitNestHost(final String nestHost) {
    if (api < Opcodes.ASM7) {
      throw new UnsupportedOperationException("This feature requires ASM7");
    }
    if (cv != null) {
      cv.visitNestHost(nestHost);
    }
  }
```
Interestingly there was a commit [manually port NEST_MATES branch changes to be compatible with ASM 6.1](https://gitlab.ow2.org/asm/asm/commit/271b59a65d7cd7d874b3e090777ad1bcb9b00545) in ASM where `ClassVisitor` had this code (i.e. without a version check):
```
public void visitNestHost(final String nestHost) {
    if (cv != null) {
      cv.visitNestHost(nestHost);
    }
  }
```

Thus it seems the only way forward is to update to ASM 7 (see [https://asm.ow2.io/versions.html](https://asm.ow2.io/versions.html)).

**Comment by petarov** [comment]
@vyazelenko  Ah, I didn't notice that line. Nicely spotted! 👍 

Going with ASM 7 probably makes sense, but maybe it needs to exit the BETA stage first, I guess.
Also, the question remains whether jdependency is compatible with ASM 7. The `master` branch seems to be on version `6.2` [[1]]( https://github.com/tcurdt/jdependency/blob/83c8f9046fc20b55fc71851b14c946b9af8a70b9/pom.xml#L44).

**Comment by johnrengelman** [comment]
@petarov if you want to test those versions, you’ll have to build a fork of shadow with them. Shadow relocates all of its dependencies, so you can’t juts upgrade them by adding them to the classpath. 

If all the tests pass, I can release a snapshot build with those versions for people to test.

**Comment by petarov** [comment]
@johnrengelman Yes, that's exactly what I did. I cloned the repo, changed the versions described above and then built the shadow jar, and used that as a plugin in my build.gradle.

I just saw that `jdependency` have released a version 2.1 with ASM 7.0-BETA as dependency. I'll test with that as soon as I have some time.

**Comment by petarov** [comment]
@johnrengelman I need some help. I wanted to test a build (just a jar file) of shadow using a `jdependency` SNAPSHOT but I can't really figure how to do that exactly. Neither of these two lines seem to work when I put them in `gradle/dependencies.gradle`.

```java
    compile fileTree(dir: 'libs', include: 'jdependency-2.2-SNAPSHOT.jar')
    // or
    compile file('<relative or full path>/jdependency-2.2-SNAPSHOT.jar')
```
The error thrown is:

```
* What went wrong:
A problem occurred evaluating project ':buildSrc'.
> No signature of method: GradlePlugins.fileTree() is applicable for argument types: (java.util.LinkedHashMap) values: [[dir:libs, include:jdependency-2.2-SNAPSHOT.jar]]
```

Any ideas?

**Comment by johnrengelman** [comment]
I published a 4.0.2-SNAPSHOT version with the dependency changes. If someone can verify that it works for JDK11, I can publish a release version.

**Comment by johnrengelman** [comment]
It’s gets published to jfrog’s snapshot repository
http://oss.jfrog.org/artifactory/simple/oss-snapshot-local/

**Comment by jamespedwards42** [comment]
ACK, It is working for me now with version `4.0.2-SNAPSHOT` and was failing with a `java.lang.UnsupportedOperationException` with version `4.0.1` using JDK 11.

**Comment by mshatalov** [comment]
`4.0.2-SNAPSHOT` fixed the issue for me as well. Thanks @petarov and @johnrengelman!

**Comment by finalchild** [comment]
`4.0.2` fixed the issue for me. Thanks!

**Comment by petarov** [comment]
All good on my side with `4.0.2` as well. Cheers! 🍻
