### ISSUE TITLE
Unable to package using openJdk11 and com.github.jengelman.gradle.plugins:shadow plugin

### ISSUE THREAD

**Issue by ebhun851** [johnrengelman/shadow#412]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

shadow jar : 4.0.1

gradle version: 4.9

java version : OpenJdk 11

### Attaching file
[Shadow_jar_Content.txt](https://github.com/johnrengelman/shadow/files/2489478/Shadow_jar_Content.txt)

**Comment by ebhun851** [comment]
Error trace as below:

org.gradle.api.GradleException: Could not add file '/opt/xyz/git/its-xyz/dist/classes/xyz/xyzAdminTool$3.class' to ZIP '/opt/xyz/git/its-xyz/dist/xyz-fat-1.10.23.32-SNAPSHOT.jar'.
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$StreamAction.visitFile(ShadowCopyAction.groovy:190)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$StreamAction.processFile(ShadowCopyAction.groovy:157)
    at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator$1$1.processFile(NormalizingCopyActionDecorator.java:66)
    at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator$1$1.processFile(DuplicateHandlingCopyActionDecorator.java:60)
    at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.processFile(CopyFileVisitorImpl.java:62)

**Comment by johnrengelman** [comment]
No. This would be a problem with ASM. This could be related to #406

**Comment by ebhun851** [comment]
Thank you @johnrengelman , somehow its not yet working either with 2.04 and 4.01. But seems like its working for others, I will have to deep dive, Will let you know
