### ISSUE TITLE
Outdated jdependency dependency causes issues with other plugins using asm.

### ISSUE THREAD

**Issue by LambdAurora** [johnrengelman/shadow#648]
### Shadow Version

6.1.0

### Gradle Version

6.8.3

### Expected Behavior

Not cause errors due to conflicting asm versions with [Fabric loom](https://github.com/FabricMC/fabric-loom).

### Actual Behavior

Errors when trying to execute buildscript due to gradle choosing shadow's jdependency bundled asm instead of the asm pulled by [Fabric loom](https://github.com/FabricMC/fabric-loom).

### Gradle Build Script(s)

[Related buildscript](https://github.com/LambdAurora/LambdaControls/blob/ab8b78f75a213c95f98ed0e5e408f4e1078aada9/build.gradle)

Related error:
```
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:70)
        at net.fabricmc.tinyremapper.TinyRemapper$3.<init>(TinyRemapper.java:429)
        at net.fabricmc.tinyremapper.TinyRemapper.analyze(TinyRemapper.java:429)
        at net.fabricmc.tinyremapper.TinyRemapper.access$400(TinyRemapper.java:65)
        at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:411)
        at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:407)
        at net.fabricmc.tinyremapper.TinyRemapper.readFile(TinyRemapper.java:407)
        at net.fabricmc.tinyremapper.TinyRemapper.access$200(TinyRemapper.java:65)
        at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:376)
        at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:372)
```

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)

Unrelated to this issue as it doesn't even build.

### Additional information

This is due to the outdated `jdependency` used by the shadow plugin.
This is a shade issue in `jdependency` that has been solved in [jdependency 2.6.0](https://github.com/tcurdt/jdependency/commit/6e233125c48a0a977f9d443b154180b7341ecc2a).

**Comment by shedaniel** [comment]
Please resolve this by updating `jdependency`!
