### ISSUE TITLE
Plugin is not working in `JDK 17 EA` build because of default strong encapsulation.

### ISSUE THREAD

**Issue by sureshg** [johnrengelman/shadow#666]
The shadow task is failing with the following error JDK 17 EA build

```
Caused by: groovy.lang.MissingPropertyException: No such property: count for class: com.github.jengelman.gradle.plugins.shadow.transformers.ServiceFileTransformer
        at groovy.lang.MetaClassImpl.invokeStaticMissingProperty(MetaClassImpl.java:1019)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1963)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1938)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3870)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:197)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:468)
        at com.github.jengelman.gradle.plugins.shadow.transformers.ServiceFileTransformer$ServiceStream.propertyMissing(ServiceFileTransformer.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:97)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaClassImpl.invokeMissingProperty(MetaClassImpl.java:879)
        at groovy.lang.MetaClassImpl$10.getProperty(MetaClassImpl.java:2120)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:85)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
        at com.github.jengelman.gradle.plugins.shadow.transformers.ServiceFileTransformer$ServiceStream.append(ServiceFileTransformer.groovy:110)
```

### Shadow Version
`id("com.github.johnrengelman.shadow") version "6.1.0"`

### Java Version

https://download.java.net/java/early_access/loom/6/openjdk-17-loom+6-225_osx-x64_bin.tar.gz

```
openjdk 17-loom 2021-09-14
OpenJDK Runtime Environment (build 17-loom+6-225)
OpenJDK 64-Bit Server VM (build 17-loom+6-225, mixed mode, sharing)
```
### Gradle Version
```
------------------------------------------------------------
Gradle 7.0
------------------------------------------------------------

Build time:   2021-04-09 22:27:31 UTC
Revision:     d5661e3f0e07a8caff705f1badf79fb5df8022c4

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          17-loom (Oracle Corporation 17-loom+6-225)
OS:           Mac OS X 10.15.7 x86_64
```
### Expected Behavior
`shadowJar` should create the uberjar.

### Actual Behavior
`shadowJar` is throwing an error on copying (`ShadowCopyAction.groovy`)

### Gradle Build Script(s)

```kotlin
    // Uber jar
    shadowJar {
        archiveClassifier.set("uber")
        description = "Create a fat JAR of $archiveFileName and runtime dependencies."
        mergeServiceFiles()
        // Don't create modular shadow jar
        exclude("module-info.class")
        // relocate("okio", "shaded.okio")
        doLast {
            val fatJar = archiveFile.get().asFile
            println("FatJar: ${fatJar.path} (${fatJar.length().toDouble() / (1_000 * 1_000)} MB)")
        }
    }
```

**Comment by sureshg** [comment]
I think instead of `super.size` (which is a `protected` field) (https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer.groovy#L110), we should use https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/io/ByteArrayOutputStream.java#L195-L197

**Comment by tofikarz** [comment]
Please update to shadow 7.0 and Gradle 7.0
