### ISSUE TITLE
gradle JavaExec deprecation warning

### ISSUE THREAD

**Issue by gurudatta-carbon** [johnrengelman/shadow#697]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version
    id "com.github.johnrengelman.shadow" version "7.0.0"

### Gradle Version
./gradlew --version

Gradle 7.1.1

Build time:   2021-07-02 12:16:43 UTC
Revision:     774525a055494e0ece39f522ac7ad17498ce032c

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8.0_292 (AdoptOpenJDK 25.292-b10)
OS:           Mac OS X 10.16 x86_64

### Expected Behavior
After running
` gradle build --warning-mode all --stacktrace
`
No deprecation warnings to be seen.

### Actual Behavior
```
 gradle build --warning-mode all --stacktrace

> Configure project :app
The JavaExec.main property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. See https://docs.gradle.org/7.1.1/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:main for more details.
        at org.gradle.api.tasks.JavaExec.setMain(JavaExec.java:418)
        at com.github.jengelman.gradle.plugins.shadow.internal.JavaJarExec_Decorated.setMain(Unknown Source)
        at org.gradle.api.tasks.JavaExec.setMain(JavaExec.java:112)
        at org.gradle.process.JavaExecSpec$setMain.call(Unknown Source)
        at com.github.jengelman.gradle.plugins.shadow.ShadowApplicationPlugin$_addRunTask_closure4.doCall(ShadowApplicationPlugin.groovy:83)
        at java.lang.reflect.Method.invoke(Method.java:498)

```

**Comment by gurudatta-carbon** [comment]
similar issue is found here https://github.com/johnrengelman/shadow/issues/609 , 
observed after creating the issue.

But seems no resolution for that? any timelines for fixing that?

**Comment by gurudatta-carbon** [comment]
There seems to be an open PR as well, https://github.com/johnrengelman/shadow/pull/686
