### ISSUE TITLE
Unsupported class file major Version 63

### ISSUE THREAD

**Issue by GamerCoder215** [johnrengelman/shadow#832]
### Shadow Version
7.1.2

### Gradle Version
7.5.2

### Expected Behavior
shadowJar builds as normal.

### Actual Behavior
```
java.lang.IllegalArgumentException: Unsupported class file major version 63
        at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)
        at jdk.internal.reflect.GeneratedConstructorAccessor388.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
```
Most of the stack trace is gradle internals.

I have to use Gradle 7.5.1 (shadowJar 8+ doesn't support it) because I'm using ForgeGradle, which doesn't support Gradle 8.
I don't know why it's reporting this even when I'm executing on Java 17 (class major version 63 is JDK 19):

```kt
// build.gradle.kts
val jvmVersionS = "17"
val jvmVersion: JavaVersion = JavaVersion.toVersion(jvmVersionS)

tasks {
    java {
        withSourcesJar()
        withJavadocJar()
        sourceCompatibility = jvmVersion
        targetCompatibility = jvmVersion
    }

    withType<KotlinCompile> {
        kotlinOptions.jvmTarget = jvmVersionS
    }
    
}
```

I'm a bit new to Gradle so if I'm doing something obviously wrong, I apologize 😅

**Comment by Goooler** [comment]
Try out https://github.com/johnrengelman/shadow/releases/tag/8.0.0.

**Comment by GamerCoder215** [comment]
> Try out https://github.com/johnrengelman/shadow/releases/tag/8.0.0.

Again, that version of shadowJar requires Gradle 8+, but I need to use ForgeGradle also, which doesn't support Gradle 8+.

Also, the issue isn't that I'm compiling with JDK 19, but that it's reading something compiled in  JDK 19, since it doesn't even exist on my computer.

**Comment by Goooler** [comment]
Doesn't backport JDK 19 support for 7.x version.

**Comment by GamerCoder215** [comment]
That's... not the issue. I don't have JDK 19 anywhere... shadowJar is reading something with JDK 19 and I don't know what it is.

**Comment by GamerCoder215** [comment]
Found what was compiling JDK 19, not an issue with shadowJar.

**Comment by IBPrivate** [comment]
and what was that? how did you corrected it?
